# Generated by Django 5.2.1 on 2025-06-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deliverypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliverypoint'),
        ),
    ]
