# Generated by Django 5.2.1 on 2025-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delivery_delivery_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
