# Generated by Django 5.2.1 on 2025-06-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delivery_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='create_at',
            new_name='added_at',
        ),
    ]
