# Generated by Django 5.2.1 on 2025-05-19 06:46

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/img/default_product.jpg', upload_to=product.models.PathAndRename()),
        ),
    ]
